language: node_js
install:
  - npm install
script:
  - npm run build
env:
  global:
    - "FTP_USER=user"
    - "FTP_PASSWORD=password"
after_success:
    "curl -T dist/* -u $FTP_USER:$FTP_PASSWORD ftp://ifest-uajy.com/dist"
