image: python:3.7.3

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install pipenv --upgrade
          - pipenv install --dev --deploy --system
          - python manage.py test
